
default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: fabricio 
  password: PostgreSQL_Role_Password

development:
  <<: *default
  database: ecommerce_api_development

  
  <<: *default
  database: ecommerce_api_test

production:
  <<: *default
  database: ecommerce_api_production
  username: ecommerce_api
  password: <%= ENV['ECOMMERCE_API_DATABASE_PASSWORD'] %>
